### ISSUE TITLE
Bundle check makes plugin very hard to use

### ISSUE THREAD

**Issue by autarch** [dagolden/Dist-Zilla-Plugin-OSPrereqs#14]
First of all, this check doesn't just catch bundles. AFAICT it will fire whenever this plugin is added programmatically from any other plugin. In my case, I'm adding this via [a custom plugin for DateTime-TimeZone](https://github.com/houseabsolute/DateTime-TimeZone/blob/master/inc/DTTZBundle.pm).

I can't move this to my `dist.ini` since I always want to depend on the latest version of `DateTime::TimeZone::Local::Win32`.

It seems like a better fix would be to replace the `log_fatal` bit with this line:

```perl
        $os = ( split /\//, $os )[-1] if $os =~ m{/};
```

**Comment by xdg** [comment]
David, can you be a bit more explicit?  Your "doesn't just catch bundles" bit is confusing phrasing.

CC: @karenetheridge -- I think this is code you added, so PTAL

**Comment by autarch** [comment]
Actually, maybe I'm wrong about it catching things other than bundles, but that's not the important part. The important part is that this isn't really doing the right thing, AFAICT.

**Comment by karenetheridge** [comment]
@autarch the heuristic is correct. You are trying to use the feature where the
plugin name is the same as the OS name, but you have already identified that
it's not, because the consuming plugin adds its name to the plugin name.  In
your case, the proper thing to do is to pass the OS name explicitly as its own
option.

However, this is not so easy at the present, first of all because it is not
documented, and second of all because the attribute has a confusing init_arg
attached to it, which I suspect is due to an erroneous copy-paste from
Dist::Zilla::Plugin::Prereqs.

I'll send a PR to OSPrereqs to correct these issues.

**Comment by xdg** [comment]
Fixed by #15
